---
version: "2"

linters:
  default: all
  disable:
    - cyclop
    - depguard
    - funlen
    - gocognit
    - gocyclo
    - gomoddirectives
    - lll
    - maintidx
    - mnd
    - nlreturn
    - nonamedreturns
    - tagalign
    - testpackage
    - tparallel
    - varnamelen
    - whitespace
    - wsl
  exclusions:
    paths:
      - builtin/
      - examples/
      - third_party/
      - vendor/
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)_test\.go
        linters:
          - dupl
          - exhaustruct
          - forcetypeassert
          - gochecknoglobals
          - gosec
          - wrapcheck
  settings:
    forbidigo:
      forbid:
        - pattern: "^(print(|ln)|fmt\\.Print(|f|ln)|log\\.(Print(|f|ln)|Fatal(|f|ln)|Panic(|f|ln))|os\\.Exit)$"
          msg: Please use slog for logging, return errors, or panic instead when appropriate.
    sloglint:
      key-naming-case: snake
      kv-only: true
      msg-style: lowercased
      static-msg: true

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - builtin/
      - examples/
      - third_party/
      - vendor/

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false

run:
  tests: true
  timeout: 100s

severity:
  default: error
