---
version: 2

project_name: go-serve-s3

before:
  hooks:
    - go mod tidy

builds:
  - id: go-serve-s3
    env:
      - CGO_ENABLED=0
    targets:
      - go_first_class
    flags:
      - -trimpath
    ldflags:
      - -s -w

changelog:
  sort: asc
  filters:
    exclude:
      - "^Merge "

archives:
  - format_overrides:
      - goos: windows
        formats: zip

checksum:
  name_template: checksums.sha256.txt
  algorithm: sha256

report_sizes: true

dockers_v2:
  - id: go-serve-s3-image
    dockerfile: Dockerfile
    ids:
      - go-serve-s3
    images:
      - yusoltsev/go-serve-s3
      - ghcr.io/yegor-usoltsev/go-serve-s3
    tags:
      - "v{{ .Version }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "v{{ .Major }}"
      - "latest"
    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.description: "Serve static files from S3 with HTTP caching"
      org.opencontainers.image.name: "{{ .ProjectName }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.source: "{{ .GitURL }}"
      org.opencontainers.image.version: "{{ .Version }}"
    platforms:
      - linux/amd64
      - linux/arm64

release:
  github:
    owner: yegor-usoltsev
    name: go-serve-s3
  name_template: "v{{ .Version }}"
  footer: |
    ## Docker images
    - [`yusoltsev/go-serve-s3:{{ .Version }}`](https://hub.docker.com/r/yusoltsev/go-serve-s3/tags?name={{ .Version }})
    - [`ghcr.io/yegor-usoltsev/go-serve-s3:{{ .Version }}`](https://github.com/yegor-usoltsev/go-serve-s3/pkgs/container/go-serve-s3)
