---
name: CI

on:
  push:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go build -race ./...
      - run: go test -v -race -timeout=100s -covermode=atomic ./...
      - uses: golangci/golangci-lint-action@v7
      - run: docker build .
